[package]
name = "sherlock"
version = "0.1.0"
authors = ["Sampo Siitonen <sampo.siitonen@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
bitflags = "1.2.1"
futures = "0.3.4"

[dependencies.async-std]
version = "1.5.0"
features = ["unstable"]

[profile.release]
debug = true