[package]
name = "sherlock"
version = "0.1.0"
authors = ["Sampo Siitonen <sampo.siitonen@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
bitflags = "1.2.1"

[profile.release]
debug = true